### ISSUE TITLE
Console is not returning userStudent: 

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#58]
Im noticing when logging into a student account, console is not returning the userStudent data. 

<img width="705" alt="Screen Shot 2020-04-15 at 2 30 52 PM" src="https://user-images.githubusercontent.com/60198845/79374914-cc84e380-7f25-11ea-990a-e291dc5aa63b.png">

**Comment by cucucachu** [comment]
Will remove all logging, none of this data needs to be in the console outside of debugging.
