### ISSUE TITLE
Creating a new school csv issues 

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#62]
<b>Issue # 1</b> - Downloading the .csv template is returning an error message

<img width="727" alt="Screen Shot 2020-04-16 at 3 11 26 PM" src="https://user-images.githubusercontent.com/60198845/79496731-906c8400-7ff4-11ea-8772-e86686a80a7d.png">

<b>Issue  # 2</b> - After filling out the required information in the .csv template, uploading the .csv file is returning an error message. Upload fails 

<img width="725" alt="Screen Shot 2020-04-16 at 3 15 41 PM" src="https://user-images.githubusercontent.com/60198845/79497111-286a6d80-7ff5-11ea-8333-c8a0bd15e86c.png">

**Comment by cucucachu** [comment]
Hi Eli, 

I can't recreate issue #1 here. Can you test again and if it is still an issue provide me with some more information to recreate it?

For issue 2, can you test again after taylors latest changes. If still failing, can you provide me with the csv files to recreate?

Thanks!

**Comment by cucucachu** [comment]
Did not mean to close issue.

**Comment by elicaballero** [comment]
Verified this is now working as expected, I was able to upload both student / professor csv's without any issues.
