### ISSUE TITLE
Session time out concern

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#63]
When an admin is registering a new school, all required fields are filled out and the admin moves to the next screen to upload StudentrRoster.csv and the ProfessorRoster.csv. Im noticing if the files are not uploaded within a certain time, the session times out. 

If the admin tries to use to the same <b>School setup key</b> they can no longer be use it to upload the csv. 

The account is still being created on the back and can be logged into

**Comment by cucucachu** [comment]
I believe this issue should now be fixed. Taylor has added a button in the front end, which allows an admin to return to the setup school page. This button can be found on the page immediately after an admin signs in.
