### ISSUE TITLE
 "Setup School Successful" without uploading csv files 

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#64]
Tested: 4/21/2020 12:56 pm

Created a new school (raroppinnagu-6196@yopmail.com PW: password1) 
After manually checking in the csv files without uploading them, console is showing a message "Setup School Successful". This message is not showing on the frontend. I still have not been able to successfully upload a csv with student/professor data.

<img width="585" alt="Screen Shot 2020-04-21 at 12 59 23 PM" src="https://user-images.githubusercontent.com/60198845/79892203-2d9e3280-83d0-11ea-9298-7e31fc77cb2f.png">

<img width="582" alt="Screen Shot 2020-04-21 at 12 56 58 PM" src="https://user-images.githubusercontent.com/60198845/79892215-30992300-83d0-11ea-962a-45f1f4b96766.png">

**Comment by cucucachu** [comment]
Added error check case to route admin/setupsSchool, 

route will now return an error if either or both the professor file or student file is missing from the request. 

@elicaballero After next redeploy, you can test and reopen if this is still an issue. It also looks like Taylor added his own error message for this case, even though he is still hitting my route.
