### ISSUE TITLE
New School email confirmation is not received for Admin

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#69]
After creating a new school, should an email confirmation be received for admin to the "School Email"? I was able to very the Student and Professor emails are being received as expected and they look good. 

<img width="752" alt="Screen Shot 2020-04-27 at 11 11 42 AM" src="https://user-images.githubusercontent.com/60198845/80388758-44350580-8878-11ea-9b37-a0ee1aa73b78.png">

<img width="594" alt="Screen Shot 2020-04-27 at 11 13 04 AM" src="https://user-images.githubusercontent.com/60198845/80388772-48f9b980-8878-11ea-87f3-95ad1d9c87f7.png">

**Comment by cucucachu** [comment]
Hey Eli.

Good question. As far as I know I haven't heard that there is any email to the admin account during creating a school, so as long as the students and professors get their emails, we're good.
