### ISSUE TITLE
Proctoring video concern 

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#78]
I am noticing when a user is in the middle of testing (video recording) - if the user goes back a page within the web browser they are able to click forward again into the proctoring page, bypassing the log in requirements and the video continues.

Concern - Should the user need to log in again with proper credentials if they accidentally go back a web page within the browser?

**Comment by cucucachu** [comment]
Good question. I think this my be a question for Ian. 

From a technical perspective, users are only 'logged out' either 4 hours after they logged in or if they click the logout button.

If we did want to enforce them logging in again, it would be a front-end job to log the user out and redirect them to the login page again.

My thoughts, I think it would be ok that the user can click back and then come back in and resume.

**Comment by cucucachu** [comment]
Closing, no change
